# Generated by Django 4.2.11 on 2024-03-12 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='face_encoding',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
